import{i as W,a as R,j as U,c as q,o as F,b as K}from"./assets/footer-CLMXpC5o.js";import"./assets/vendor-Bie5rgBU.js";W();document.addEventListener("DOMContentLoaded",()=>{R();const y=document.getElementById("searchInput"),f=document.getElementById("yearSelectWrapper"),P=document.getElementById("searchForm"),s=document.getElementById("yearMenu"),d=document.querySelector(".custom-select__trigger"),E=document.querySelector(".custom-select__label"),n=document.querySelector(".catalog-movies-list"),m=document.getElementById("clearBtnDesktop"),u=document.getElementById("clearBtnMobile"),v=document.getElementById("mobileCloneBox"),c=document.getElementById("paginationWrapper"),h=document.getElementById("paginationNumbers"),D=document.getElementById("prevPageBtn"),S=document.getElementById("nextPageBtn");let a=1,p=1,w="",$="",C=!1,l=0,r=[];async function I(){try{C=!1,c&&(c.style.display="none"),n&&(n.innerHTML='<div class="catalog-loading">Loading trending movies...</div>');const e=await K("day"),t=e?e.results:null;if(!t||!Array.isArray(t)||t.length===0){n.innerHTML='<div class="catalog-error-message"><p>No trending movies found.</p></div>';return}n.innerHTML="",await Y(t,!1)}catch(e){n&&(n.innerHTML=`<div class="catalog-error-message"><p>${e.message||"An error occurred."}</p></div>`)}}I(),P.addEventListener("submit",async e=>{if(e.preventDefault(),w=y.value.trim(),$=E.textContent==="Year"?"":E.textContent,!w){n.innerHTML='<div class="catalog-error-message"><p>Please enter a movie title to search.</p></div>',c&&(c.style.display="none");return}C=!0,a=1,await _()});async function _(){try{n.innerHTML='<div class="catalog-loading">Searching movies...</div>',window.scrollTo({top:0,behavior:"smooth"});const e=await U(w,a,$),t=e?e.results:null;if(p=e?Math.min(e.total_pages,500):1,!t||t.length===0){n.innerHTML=`
          <div class="catalog-error-message">
            <h2>OOPS...</h2>
            <p>We are very sorry!</p>
            <p>We don’t have any results matching your search.</p>
          </div>
        `,c&&(c.style.display="none");return}n.innerHTML="",await Y(t,!1),z()}catch(e){n.innerHTML=`<div class="catalog-error-message"><p>${e.message||"An error occurred."}</p></div>`}}function z(){if(!C||p<=1){c&&(c.style.display="none");return}c&&(c.style.display="flex"),h.innerHTML="",D.disabled=a===1,S.disabled=a===p;const e=1;for(let t=1;t<=p;t++)if(t===1||t===p||t>=a-e&&t<=a+e){const i=document.createElement("button");i.type="button",i.className=`pagination-btn ${t===a?"is-active":""}`,i.textContent=t<10?`0${t}`:t,i.addEventListener("click",()=>{a=t,_()}),h.appendChild(i)}else if((t===2||t===p-1)&&(!h.lastChild||h.lastChild.textContent!=="...")){const i=document.createElement("span");i.className="pagination-dots",i.textContent="...",h.appendChild(i)}}D.addEventListener("click",()=>{a>1&&(a--,_())}),S.addEventListener("click",()=>{a<p&&(a++,_())});async function Y(e,t=!1){if(n){t||(n.innerHTML="");for(const i of e){const o=document.createElement("div");o.className="movie-card";const B=i.poster_path?`https://image.tmdb.org/t/p/w500${i.poster_path}`:"https://placehold.co/400x400?text=No+Image",g=i.release_date?i.release_date.split("-")[0]:"Unknown";let M="Unknown";i.genre_ids&&i.genre_ids.length>0&&(M=(await q(i.genre_ids)).slice(0,2).join(", "));const L=Math.round(i.vote_average/2),x="★".repeat(L)+"☆".repeat(5-L);o.innerHTML=`
        <img class="movie-card__poster" src="${B}" alt="${i.title}" loading="lazy">
        <div class="movie-card__overlay">
          <h2 class="movie-card__title">${i.title}</h2>
          <div class="movie-card__meta">
            <div class="movie-card__details">${M} | ${g}</div>
            <div class="movie-card__stars">${x}</div>
          </div>
        </div>
      `,o.addEventListener("click",()=>{F(i)}),n.appendChild(o)}}}function N(){const e=new Date().getFullYear(),t=1900;let i='<li class="custom-select__option custom-select__option--default" data-value="">Year</li>';for(let o=e;o>=t;o--)i+=`<li class="custom-select__option" data-value="${o}">${o}</li>`;i+='<li class="custom-select__spacer"></li>',s.innerHTML=i,r=Array.from(s.querySelectorAll(".custom-select__option"))}N();function A(){if(r.length===0)return;const e=s.getBoundingClientRect(),t=e.top+e.height/2;let i=r[0],o=1/0,B=0;r.forEach((g,M)=>{const L=g.getBoundingClientRect(),x=L.top+L.height/2,H=Math.abs(t-x);H<o&&(o=H,i=g,B=M)}),r.forEach(g=>g.classList.remove("is-active")),i&&i.classList.add("is-active"),l=B}s.addEventListener("scroll",A),d.addEventListener("click",e=>{e.stopPropagation(),s.classList.toggle("hide")?k():(d.classList.add("is-open"),setTimeout(()=>{b()},50))});function k(){if(s.classList.add("hide"),d.classList.remove("is-open"),r[l]){const e=r[l].getAttribute("data-value");E.textContent=e||"Year"}}function b(){r[l]&&(r[l].scrollIntoView({behavior:"smooth",block:"center"}),A())}s.addEventListener("click",e=>{if(e.target.classList.contains("custom-select__option")){const t=r.indexOf(e.target);t!==-1&&(l=t,b(),setTimeout(k,300))}}),d.addEventListener("keydown",e=>{if(s.classList.contains("hide")&&(e.key==="ArrowDown"||e.key==="ArrowUp"||e.key==="Enter")){e.preventDefault(),d.click();return}e.key==="ArrowDown"?(e.preventDefault(),l<r.length-1&&(l++,b())):e.key==="ArrowUp"?(e.preventDefault(),l>0&&(l--,b())):e.key==="Enter"?(e.preventDefault(),k()):e.key==="Escape"&&(e.preventDefault(),s.classList.add("hide"),d.classList.remove("is-open"))}),document.addEventListener("click",k),y.addEventListener("input",e=>{const t=e.target.value.trim(),i=document.getElementById("searchClone");t.length>0?(window.innerWidth<1200?(v&&v.classList.add("is-active"),f&&f.classList.add("is-visible"),i&&(i.value=t),u&&(u.style.display="block"),m&&(m.style.display="none")):(v&&v.classList.remove("is-active"),f&&f.classList.add("is-visible"),m&&(m.style.display="block"),u&&(u.style.display="none")),s&&s.classList.add("hide")):T()});function T(){y.value="",m&&(m.style.display="none"),u&&(u.style.display="none"),v&&v.classList.remove("is-active"),f&&f.classList.remove("is-visible"),s&&s.classList.add("hide"),d&&d.classList.remove("is-open"),E.textContent="Year",l=0}m&&m.addEventListener("click",()=>{T(),y.focus(),I()}),u&&u.addEventListener("click",()=>{T(),y.focus(),I()})});
//# sourceMappingURL=catalog.js.map
