import{i as q,a as N,f as G,s as O,c as A}from"./assets/hero-CYO8h5CC.js";import"./assets/vendor-Bie5rgBU.js";i;let o,m,r,S,u,g,l,h,v,E,s,L=1,y=1,M="",x="",w=!1;function k(){o&&(o.innerHTML='<li class="global-loader__spinner" style="margin: 40px auto; display: block;"></li>'),m&&m.classList.add("hidden")}function p(n){n?(m&&m.classList.remove("hidden"),o&&(o.innerHTML="")):m&&m.classList.add("hidden")}function B(n,e){if(!r||(r.innerHTML="",e<=1))return;const t=Math.min(e,20),a=document.createElement("button");a.className="pagination__btn",a.textContent="←",a.disabled=n===1,a.addEventListener("click",()=>b(n-1)),r.appendChild(a),D(n,t).forEach(f=>{if(f==="..."){const C=document.createElement("span");C.className="pagination__dots",C.textContent="...",r.appendChild(C);return}const d=document.createElement("button");d.className="pagination__btn",d.textContent=f,f===n&&d.classList.add("active"),d.addEventListener("click",()=>b(f)),r.appendChild(d)});const c=document.createElement("button");c.className="pagination__btn",c.textContent="→",c.disabled=n===t,c.addEventListener("click",()=>b(n+1)),r.appendChild(c)}function D(n,e){if(e<=7){const t=[];for(let a=1;a<=e;a++)t.push(a);return t}return n<=4?[1,2,3,4,5,"...",e]:n>=e-3?[1,"...",e-4,e-3,e-2,e-1,e]:[1,"...",n-1,n,n+1,"...",e]}function _(n){!s||!v||(s.classList.toggle("hide",!n),v.setAttribute("aria-expanded",n?"true":"false"))}function T(n,e){l&&(l.value=n),E&&(E.textContent=e),s&&s.querySelectorAll("li").forEach(t=>{t.classList.toggle("selected",t.dataset.value===String(n))})}function F(){if(h=document.getElementById("yearSelectCustom"),!h||!l||(v=h.querySelector(".custom-select__btn"),E=h.querySelector(".custom-select__label"),s=h.querySelector(".custom-select__list"),!v||!E||!s))return;s.innerHTML="";const n=document.createElement("li");n.dataset.value="",n.textContent="Year",s.appendChild(n),Array.from(l.options).forEach(e=>{if(e.value==="")return;const t=document.createElement("li");t.dataset.value=e.value,t.textContent=e.textContent,s.appendChild(t)}),T(l.value,"Year"),_(!1),v.addEventListener("click",e=>{e.stopPropagation();const t=!s.classList.contains("hide");_(!t)}),s.addEventListener("click",e=>{const t=e.target.closest("li");t&&(T(t.dataset.value,t.textContent),_(!1))}),document.addEventListener("click",()=>{_(!1)})}function b(n){n<1||n>Math.min(y,20)||(w?$(M,n,x):H(n))}function P(){const n=document.querySelector(".catalog-section");if(n){const e=document.querySelector(".header"),t=e?e.offsetHeight:0,a=Math.max(n.offsetTop-t-40,0);window.scrollTo({top:a,behavior:"smooth"})}}async function Y(n){if(!o)return;const e=await Promise.all(n.map(async t=>{const a=await A(t.genre_ids||[]),I=t.release_date?t.release_date.slice(0,4):"—",c=t.poster_path?`https://image.tmdb.org/t/p/w500${t.poster_path}`:"./img/oops-logo.png",f=t.vote_average||0,d=generateStarIconsMarkup(f,"movie-card__star");return`
      <li class="movie-card" data-id="${t.id}">
        <img src="${c}" alt="${t.title}" class="movie-card__poster" loading="lazy" />
        <div class="movie-card__info">
          <h3 class="movie-card__title">${t.title}</h3>
          <div class="movie-card__meta">
            <span class="movie-card__text">${a.slice(0,2).join(", ")} | ${I}</span>
            <div class="movie-card__stars">${d}</div>
          </div>
        </div>
      </li>
    `}));o.innerHTML=e.join("")}async function H(n){k();try{const e=await G(n);if(L=n,y=e.total_pages,!e.results||e.results.length===0){p(!0),r&&(r.innerHTML="");return}p(!1),await Y(e.results),B(L,y),P()}catch(e){console.error(e),p(!0)}}async function $(n,e,t=""){k();try{const a=await O(n,e,t);if(L=e,y=a.total_pages,!a.results||a.results.length===0){p(!0),r&&(r.innerHTML="");return}p(!1),await Y(a.results),B(L,y),P()}catch(a){console.error(a),p(!0)}}async function j(){initGlobalUi(),q(),o=document.getElementById("movieGrid"),m=document.getElementById("oopsMessage"),r=document.getElementById("pagination"),S=document.getElementById("searchForm"),u=document.getElementById("searchInput"),g=document.getElementById("clearBtn"),l=document.getElementById("yearSelect");const n=new Date().getFullYear();for(let e=n;e>=1900;e--){const t=document.createElement("option");t.value=e,t.textContent=e,l.appendChild(t)}F(),u&&u.addEventListener("input",()=>{g&&(g.hidden=u.value.trim()==="")}),g&&g.addEventListener("click",()=>{u.value="",T("","Year"),g.hidden=!0,u.focus(),w=!1,M="",x="",H(1)}),S&&S.addEventListener("submit",e=>{e.preventDefault();const t=u.value.trim(),a=l.value;t&&(w=!0,M=t,x=a,$(t,1,a))}),o&&o.addEventListener("click",e=>{const t=e.target.closest(".movie-card");t&&showMovieSpotlight(t.dataset.id)}),await Promise.allSettled([N(),H(1)])}document.addEventListener("DOMContentLoaded",j,{once:!0});
//# sourceMappingURL=catalog.js.map
