import{i as W,a as R,s as U,c as q,b as F}from"./assets/footer-BGGYMWA1.js";import"./assets/main-hDvGAroS.js";import"./assets/vendor-Bie5rgBU.js";W();document.addEventListener("DOMContentLoaded",()=>{R();const m=document.getElementById("searchInput"),v=document.getElementById("yearSelectWrapper"),$=document.getElementById("searchForm"),n=document.getElementById("yearMenu"),l=document.querySelector(".custom-select__trigger"),h=document.querySelector(".custom-select__label"),s=document.querySelector(".catalog-movies-list"),u=document.getElementById("clearBtnDesktop"),f=document.getElementById("clearBtnMobile"),g=document.getElementById("mobileCloneBox"),d=document.getElementById("paginationWrapper"),L=document.getElementById("paginationNumbers"),w=document.getElementById("prevPageBtn"),I=document.getElementById("nextPageBtn");let a=1,p=1,C="",Y="",T=!1,r=0,c=[];async function x(){try{T=!1,d&&(d.style.display="none"),s&&(s.innerHTML='<div class="catalog-loading">Loading trending movies...</div>');const e=await F("day"),t=e?e.results:null;if(!t||!Array.isArray(t)||t.length===0){s.innerHTML='<div class="catalog-error-message"><p>No trending movies found.</p></div>';return}s.innerHTML="",await A(t,!1)}catch(e){s&&(s.innerHTML=`<div class="catalog-error-message"><p>${e.message||"An error occurred."}</p></div>`)}}x(),$&&$.addEventListener("submit",async e=>{if(e.preventDefault(),C=m.value.trim(),Y=h.textContent==="Year"?"":h.textContent,!C){s.innerHTML='<div class="catalog-error-message"><p>Please enter a movie title to search.</p></div>',d&&(d.style.display="none");return}T=!0,a=1,await _()});async function _(){try{s.innerHTML='<div class="catalog-loading">Searching movies...</div>',window.scrollTo({top:0,behavior:"smooth"});const e=await U(C,a,Y),t=e?e.results:null;if(p=e?Math.min(e.total_pages,500):1,!t||t.length===0){s.innerHTML=`
          <div class="catalog-error-message">
            <h2>OOPS...</h2>
            <p>We are very sorry!</p>
            <p>We don’t have any results matching your search.</p>
          </div>
        `,d&&(d.style.display="none");return}s.innerHTML="",await A(t,!1),z()}catch(e){s.innerHTML=`<div class="catalog-error-message"><p>${e.message||"An error occurred."}</p></div>`}}function z(){if(!T||p<=1){d&&(d.style.display="none");return}d&&(d.style.display="flex"),L.innerHTML="",w.disabled=a===1,I.disabled=a===p;const e=1;for(let t=1;t<=p;t++)if(t===1||t===p||t>=a-e&&t<=a+e){const i=document.createElement("button");i.type="button",i.className=`pagination-btn ${t===a?"is-active":""}`,i.textContent=t<10?`0${t}`:t,i.addEventListener("click",()=>{a=t,_()}),L.appendChild(i)}else if((t===2||t===p-1)&&(!L.lastChild||L.lastChild.textContent!=="...")){const i=document.createElement("span");i.className="pagination-dots",i.textContent="...",L.appendChild(i)}}w&&w.addEventListener("click",()=>{a>1&&(a--,_())}),I&&I.addEventListener("click",()=>{a<p&&(a++,_())});async function A(e,t=!1){if(s){t||(s.innerHTML="");for(const i of e){const o=document.createElement("div");o.className="movie-card";const B=i.poster_path?`https://image.tmdb.org/t/p/w500${i.poster_path}`:"https://placehold.co/400x400?text=No+Image",y=i.release_date?i.release_date.split("-")[0]:"Unknown";let M="Unknown";i.genre_ids&&i.genre_ids.length>0&&(M=(await q(i.genre_ids)).slice(0,2).join(", "));const E=Math.round(i.vote_average/2),H="★".repeat(E)+"☆".repeat(5-E);o.innerHTML=`
        <img class="movie-card__poster" src="${B}" alt="${i.title}" loading="lazy">
        <div class="movie-card__overlay">
          <h2 class="movie-card__title">${i.title}</h2>
          <div class="movie-card__meta">
            <div class="movie-card__details">${M} | ${y}</div>
            <div class="movie-card__stars">${H}</div>
          </div>
        </div>
      `,o.addEventListener("click",()=>{console.log(`Selected Movie ID: ${i.id}`)}),s.appendChild(o)}}}function N(){if(!n)return;const e=new Date().getFullYear(),t=1900;let i='<li class="custom-select__option custom-select__option--default" data-value="">Year</li>';for(let o=e;o>=t;o--)i+=`<li class="custom-select__option" data-value="${o}">${o}</li>`;i+='<li class="custom-select__spacer"></li>',n.innerHTML=i,c=Array.from(n.querySelectorAll(".custom-select__option"))}N();function P(){if(c.length===0||!n)return;const e=n.getBoundingClientRect(),t=e.top+e.height/2;let i=c[0],o=1/0,B=0;c.forEach((y,M)=>{const E=y.getBoundingClientRect(),H=E.top+E.height/2,S=Math.abs(t-H);S<o&&(o=S,i=y,B=M)}),c.forEach(y=>y.classList.remove("is-active")),i&&i.classList.add("is-active"),r=B}n&&n.addEventListener("scroll",P),l&&l.addEventListener("click",e=>{e.stopPropagation(),n.classList.toggle("hide")?k():(l.classList.add("is-open"),setTimeout(()=>{b()},50))});function k(){if(!(!n||!l)&&(n.classList.add("hide"),l.classList.remove("is-open"),c[r])){const e=c[r].getAttribute("data-value");h.textContent=e||"Year"}}function b(){c[r]&&(c[r].scrollIntoView({behavior:"smooth",block:"center"}),P())}n&&n.addEventListener("click",e=>{if(e.target.classList.contains("custom-select__option")){const t=c.indexOf(e.target);t!==-1&&(r=t,b(),setTimeout(k,300))}}),l&&l.addEventListener("keydown",e=>{if(n.classList.contains("hide")&&(e.key==="ArrowDown"||e.key==="ArrowUp"||e.key==="Enter")){e.preventDefault(),l.click();return}e.key==="ArrowDown"?(e.preventDefault(),r<c.length-1&&(r++,b())):e.key==="ArrowUp"?(e.preventDefault(),r>0&&(r--,b())):e.key==="Enter"?(e.preventDefault(),k()):e.key==="Escape"&&(e.preventDefault(),n.classList.add("hide"),l.classList.remove("is-open"))}),document.addEventListener("click",k),m&&m.addEventListener("input",e=>{const t=e.target.value.trim(),i=document.getElementById("searchClone");t.length>0?(window.innerWidth<1200?(g&&g.classList.add("is-active"),v&&v.classList.add("is-visible"),i&&(i.value=t),f&&(f.style.display="block"),u&&(u.style.display="none")):(g&&g.classList.remove("is-active"),v&&v.classList.add("is-visible"),u&&(u.style.display="block"),f&&(f.style.display="none")),n&&n.classList.add("hide")):D()});function D(){m&&(m.value=""),u&&(u.style.display="none"),f&&(f.style.display="none"),g&&g.classList.remove("is-active"),v&&v.classList.remove("is-visible"),n&&n.classList.add("hide"),l&&l.classList.remove("is-open"),h&&(h.textContent="Year"),r=0}u&&u.addEventListener("click",()=>{D(),m&&m.focus(),x()}),f&&f.addEventListener("click",()=>{D(),m&&m.focus(),x()})});
//# sourceMappingURL=catalog.js.map
