import{i as C,a as I,g as G,c as M}from"./assets/footer-BGGYMWA1.js";import"./assets/vendor-Bie5rgBU.js";let p=0;function y(){let e=document.getElementById("globalLoader");return e||(e=document.createElement("div"),e.id="globalLoader",e.className="global-loader hidden",e.innerHTML='<div class="global-loader__spinner" aria-hidden="true"></div>',document.body.appendChild(e),e)}function k(){let e=document.getElementById("scrollUpButton");return e||(e=document.createElement("button"),e.id="scrollUpButton",e.className="scroll-up hidden",e.type="button",e.setAttribute("aria-label","Scroll to top"),e.textContent="↑",document.body.appendChild(e),e)}function x(){const e=y();p+=1,e.classList.remove("hidden")}function H(){const e=y();p=Math.max(0,p-1),p===0&&e.classList.add("hidden")}function $(){const e=k();if(y(),e.dataset.bound==="true")return;const t=()=>{e.classList.toggle("hidden",window.scrollY<320)};window.addEventListener("scroll",t,{passive:!0}),e.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})}),t(),e.dataset.bound="true"}const P="cinemania-saved-movies";function S(){try{const e=localStorage.getItem(P);return e?JSON.parse(e):[]}catch(e){return reportError("Saved movies error:",e),[]}}let l=[],m=[],v=1;const L=9;async function _(){$(),C(),x();try{await I(),await T()}catch(e){console.error("Library yüklenirken hata oluştu:",e)}finally{H()}}async function T(){const e=document.getElementById("libraryGallery"),t=document.getElementById("loadMore"),i=document.getElementById("genreFilter");if(!e)return;if(l=S(),m=[...l],l.length===0){w(e,t,i);return}const c=await G();B(i,c,e,t),h(e,t),t&&t.addEventListener("click",()=>{v++,h(e,t)}),e.addEventListener("click",n=>{const d=n.target.closest(".movie-card");d&&console.log("Seçilen film ID:",d.dataset.id)}),document.addEventListener("cinemania:library:add",()=>E(e,t)),document.addEventListener("cinemania:library:remove",()=>E(e,t))}function w(e,t,i){t&&t.classList.add("is-hidden"),i&&i.classList.add("is-hidden"),e.innerHTML=`
    <div class="empty-state">
      <p class="empty-text">OOPS...<br>We are very sorry!<br>You don't have any movies<br>at your library.</p>
      <a href="./catalog.html" class="btn-search-more">Search Movie</a>
    </div>
  `}function B(e,t,i,c){if(!e)return;const n=e.querySelector(".custom-select__list"),d=e.querySelector(".custom-select__button"),a=e.querySelector(".custom-select__label");if(!n||!d||!a)return;const g=new Set;l.forEach(s=>{var r;return(r=s.genre_ids)==null?void 0:r.forEach(o=>g.add(o))});const u=document.createElement("li");u.dataset.value="all",u.textContent="All Genres",u.classList.add("selected"),n.appendChild(u),g.forEach(s=>{const r=t.get(s);if(r){const o=document.createElement("li");o.dataset.value=s,o.textContent=r,n.appendChild(o)}}),d.addEventListener("click",s=>{s.stopPropagation(),n.classList.toggle("hide")}),document.addEventListener("click",s=>{e.contains(s.target)||n.classList.add("hide")}),n.addEventListener("click",s=>{const r=s.target.closest("li");if(!r)return;n.querySelectorAll("li").forEach(f=>f.classList.remove("selected")),r.classList.add("selected"),a.textContent=r.textContent,n.classList.add("hide");const o=r.dataset.value;v=1,i.innerHTML="",m=o==="all"?l:l.filter(f=>{var b;return(b=f.genre_ids)==null?void 0:b.includes(Number(o))}),h(i,c)})}async function h(e,t){const i=(v-1)*L,c=i+L,n=m.slice(i,c);c>=m.length?t&&t.classList.add("is-hidden"):t&&t.classList.remove("is-hidden");const d=await Promise.all(n.map(async a=>{var o;const g=((o=a.genre_names)==null?void 0:o.length)>0?a.genre_names:await M(a.genre_ids||[]),u=a.release_date?a.release_date.slice(0,4):"—",s=a.poster_path?`https://image.tmdb.org/t/p/w500${a.poster_path}`:"./img/oops-logo.png",r=(a.vote_average||0).toFixed(1);return`
        <li class="movie-card" data-id="${a.id}">
          <div class="movie-card__thumb">
            <img class="movie-card__img" src="${s}" alt="${a.title}" loading="lazy" />
            <div class="movie-card__overlay">
              <span class="movie-card__rating">${r}</span>
            </div>
          </div>
          <h3 class="movie-card__title">${a.title}</h3>
          <div class="movie-card__meta">
            <p>${g.slice(0,2).join(", ")} | ${u}</p>
          </div>
        </li>`}));e.innerHTML+=d.join("")}function E(e,t){if(l=S(),m=[...l],v=1,e.innerHTML="",l.length===0){w(e,t);return}h(e,t)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",_,{once:!0}):_();
//# sourceMappingURL=library.js.map
